wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1717169437.0
    t:
      1:
      - 1
      - 2
      - 3
      - 12
      - 41
      - 55
      - 105
      2:
      - 1
      - 2
      - 3
      - 12
      - 41
      - 55
      - 105
      3:
      - 13
      - 23
      4: 3.10.12
      5: 0.16.6
      8:
      - 1
      - 5
      13: linux-x86_64
Batch:
  desc: null
  value: 2
size_image:
  desc: null
  value: 224
